- Z:
  - 1
  - 1
  add_species: false
  compact_clusters: true
  covariance_type: ard_se
  cutoff: 3.0
  cutoff_transition_width: 0.6
  delta: 1.8045218989568328
  distance_Nb: true
  f0: 0.0
  n_sparse: 15
  order: 2
  sparse_method: uniform
  theta_uniform: 0.6
- Z:
  - 1
  - 8
  add_species: false
  compact_clusters: true
  covariance_type: ard_se
  cutoff: 3.6
  cutoff_transition_width: 0.72
  delta: 1.8045218989568328
  distance_Nb: true
  f0: 0.0
  n_sparse: 15
  order: 2
  sparse_method: uniform
  theta_uniform: 0.72
- Z:
  - 8
  - 8
  add_species: false
  compact_clusters: true
  covariance_type: ard_se
  cutoff: 4.2
  cutoff_transition_width: 0.85
  delta: 1.8045218989568328
  distance_Nb: true
  f0: 0.0
  n_sparse: 15
  order: 2
  sparse_method: uniform
  theta_uniform: 0.85
- Z: 1
  add_species: false
  atom_sigma: 0.3
  central_weight: 1.0
  covariance_type: dot_product
  cutoff: 1.2
  cutoff_transition_width: 0.3
  delta: 0.05937834584756682
  f0: 0.0
  l_max: 3
  n_max: 12
  n_sparse: 1000
  n_species: 2
  print_sparse_index: true
  soap: true
  sparse_method: cur_points
  species_Z:
  - 1
  - 8
  zeta: 4
- Z: 1
  add_species: false
  atom_sigma: 0.45
  central_weight: 1.0
  covariance_type: dot_product
  cutoff: 1.8
  cutoff_transition_width: 0.45
  delta: 0.05937834584756682
  f0: 0.0
  l_max: 3
  n_max: 12
  n_sparse: 1000
  n_species: 2
  print_sparse_index: true
  soap: true
  sparse_method: cur_points
  species_Z:
  - 1
  - 8
  zeta: 4
- Z: 1
  add_species: false
  atom_sigma: 0.68
  central_weight: 1.0
  covariance_type: dot_product
  cutoff: 2.7
  cutoff_transition_width: 0.68
  delta: 0.05937834584756682
  f0: 0.0
  l_max: 3
  n_max: 12
  n_sparse: 1000
  n_species: 2
  print_sparse_index: true
  soap: true
  sparse_method: cur_points
  species_Z:
  - 1
  - 8
  zeta: 4
- Z: 8
  add_species: false
  atom_sigma: 0.43
  central_weight: 1.0
  covariance_type: dot_product
  cutoff: 1.7
  cutoff_transition_width: 0.43
  delta: 0.05937834584756682
  f0: 0.0
  l_max: 3
  n_max: 12
  n_sparse: 1000
  n_species: 2
  print_sparse_index: true
  soap: true
  sparse_method: cur_points
  species_Z:
  - 1
  - 8
  zeta: 4
- Z: 8
  add_species: false
  atom_sigma: 0.64
  central_weight: 1.0
  covariance_type: dot_product
  cutoff: 2.6
  cutoff_transition_width: 0.64
  delta: 0.05937834584756682
  f0: 0.0
  l_max: 3
  n_max: 12
  n_sparse: 1000
  n_species: 2
  print_sparse_index: true
  soap: true
  sparse_method: cur_points
  species_Z:
  - 1
  - 8
  zeta: 4
- Z: 8
  add_species: false
  atom_sigma: 0.96
  central_weight: 1.0
  covariance_type: dot_product
  cutoff: 3.8
  cutoff_transition_width: 0.96
  delta: 0.05937834584756682
  f0: 0.0
  l_max: 3
  n_max: 12
  n_sparse: 1000
  n_species: 2
  print_sparse_index: true
  soap: true
  sparse_method: cur_points
  species_Z:
  - 1
  - 8
  zeta: 4
